stages:
- build
- test

build:
    stage: build
    script:
    - command build
    only:
        - CDCI_test
    # artifacts:
    #     paths:
    #     - build/
    
test:
    stage: test
    script:
    - command test
    only:
        - CDCI_test
